apiVersion: v1
kind: Pod
metadata:
        name: pytorch-cuda10.2
spec:
        restartPolicy: Never
        containers:
                - name: pytorch-wyy-three-container
                  image: docker.io/library/pytorch-wyy:1.2
                  imagePullPolicy: Never
                  command: ["sleep"]
                  args: ["infinity"]
                  resources:
                          requests:
                                  tencent.com/vcuda-core: 50
                                  tencent.com/vcuda-memory: 30
                          limits:
                               tencent.com/vcuda-core: 50
                               tencent.com/vcuda-memory: 30
                  env:
                    - name: LOGGER_LEVEL
                      value: "5"

